SELECT COUNT(ID)
  FROM VISUAL.THREADS

  SELECT COUNT(ID)
  FROM VISUAL.USERS
  
  SELECT ID, TITLE, BODY FROM VISUAL.THREADS WHERE ID = 34571
  SELECT ID, TITLE, BODY FROM VISUAL.THREADS WHERE ID = 55709
  SELECT ID, TITLE, BODY FROM VISUAL.THREADS WHERE ID = 46663
  SELECT ID, TITLE, BODY FROM VISUAL.THREADS WHERE ID = 45623
  SELECT ID, TITLE, BODY FROM VISUAL.THREADS WHERE ID = 25331