SELECT S.POSTID, S.POSTPARENTID AS THREADID, P.* FROM VISUAL.PATTERN_2_POST S RIGHT JOIN VISUAL.PATTERNS P ON S.PATTERNNAME = P.PATTERNNAME;

SELECT * FROM VISUAL.CLASSIFIED_THREAD WHERE ID = '1837635';
SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID = '1837635';

SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID = 65058;
SELECT * FROM VISUAL.THREADS WHERE ID = 15496;

SELECT * FROM ( SELECT ROW_NUMBER() OVER() AS RANK, U.* FROM (SELECT * FROM VISUAL.USERS ORDER BY REPUTATION DESC) U ) I WHERE I.ID = 893 

DROP VIEW VISUAL.RANKED_USERS;

CREATE VIEW VISUAL.RANKED_USERS (RANK, ID, DISPLAYNAME, REPUTATION) AS (SELECT ROW_NUMBER() OVER() AS RANK, U.* FROM (SELECT * FROM VISUAL.USERS ORDER BY REPUTATION DESC) U);

SELECT * FROM VISUAL.RANKED_USERS WHERE ID=893;

select COUNT(*)+1 as rank from VISUAL.USERS  where REPUTATION > (select REPUTATION from VISUAL.USERS where ID = 893);

SELECT COUNT(*) + 1 AS CNT FROM VISUAL.USERS WHERE REPUTATION < (SELECT REPUTATION FROM VISUAL.USERS WHERE ID = 893);

SELECT MAX(REPUTATION) AS MAX_REPUTATION FROM VISUAL.USERS

SELECT * FROM (SELECT ROW_NUMBER() OVER () AS rownumber, T.* FROM (SELECT * FROM VISUAL.USERS ORDER BY REPUTATION DESC) T) AS U WHERE rownumber = 3

SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID = 25552 AND THREADID != THREADID2 AND THREADID2 IS NOT NULL AND SIMILARITY > 0 AND THREADID2 IN (SELECT ID FROM VISUAL.CLASSIFIED_THREAD) ORDER BY SIMILARITY FETCH FIRST 500 ROWS ONLY FOR READ ONLY

SELECT * FROM VISUAL.THREADS T WHERE POSTTYPEID = 2 AND PARENTID = 11088 FOR READ ONLY

DROP TABLE VISUAL.PATTERNS;

SELECT MAX(X) AS MAX_X, MIN(X) AS MIN_X, MAX(Y) AS MAX_Y, MIN(Y) AS MIN_Y FROM VISUAL.SVD_THREADS

SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID2 = 40663;
SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID = 35785 AND THREADID2 = 40663;
SELECT * FROM VISUAL.SIMILARITIES WHERE THREADID2 = 35785 AND THREADID = 40663;
